version: '3'

services:
  forntend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: ./server
    ports:
      - "6969:6969"
  mongo:
    image: mongo:focal
    ports:
      - "27017:27017"
    volumes:
      - myapp:/etc/mongo
volumes:
  myapp:
