name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: "ubuntu-20.04"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker compose
        id: build-image
        run: |
          apt-get update && apt-get upgrade && docker-compose build

